# Generated by Django 5.2.6 on 2025-09-11 13:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titolo')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('content', models.TextField(verbose_name='Contenuto')),
                ('summary', models.TextField(help_text="Breve riassunto dell'articolo", max_length=300, verbose_name='Riassunto')),
                ('category', models.CharField(choices=[('commerciale', 'Diritto Commerciale'), ('privato', 'Diritto Privato'), ('lavoro', 'Diritto del Lavoro')], max_length=20, verbose_name='Categoria')),
                ('published', models.BooleanField(default=False, verbose_name='Pubblicato')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data creazione')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data ultima modifica')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autore')),
            ],
            options={
                'verbose_name': 'Articolo',
                'verbose_name_plural': 'Articoli',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='news_articl_created_a034b3_idx'), models.Index(fields=['category'], name='news_articl_categor_5c78fc_idx'), models.Index(fields=['published'], name='news_articl_publish_e1f004_idx')],
            },
        ),
    ]
