# Generated by Django 5.1.4 on 2025-09-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, help_text="Immagine principale dell'articolo", null=True, upload_to='articles/', verbose_name='Immagine'),
        ),
    ]
