# Generated by Django 5.1.4 on 2025-09-11 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_article_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='articles/gallery/', verbose_name='Immagine')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Didascalia')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordine')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data creazione')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='news.article', verbose_name='Articolo')),
            ],
            options={
                'verbose_name': 'Immagine Articolo',
                'verbose_name_plural': 'Immagini Articolo',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
