# Generated by Django 5.1.4 on 2025-09-13 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_articleimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Chi Siamo', max_length=255, verbose_name='Titolo')),
                ('content', models.TextField(help_text="Descrizione dell'azienda e dei suoi scopi", verbose_name='Contenuto')),
                ('mission', models.TextField(blank=True, help_text='La nostra missione', verbose_name='Missione')),
                ('vision', models.TextField(blank=True, help_text='La nostra visione', verbose_name='Visione')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='Immagine principale')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data creazione')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data ultima modifica')),
            ],
            options={
                'verbose_name': 'Chi Siamo',
                'verbose_name_plural': 'Chi Siamo',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome e Cognome')),
                ('role', models.CharField(choices=[('director', 'Direttore'), ('editor', 'Editore'), ('lawyer', 'Avvocato'), ('journalist', 'Giornalista'), ('researcher', 'Ricercatore'), ('other', 'Altro')], max_length=20, verbose_name='Ruolo')),
                ('bio', models.TextField(verbose_name='Biografia')),
                ('image', models.ImageField(blank=True, null=True, upload_to='team/', verbose_name='Foto')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordine di visualizzazione')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data creazione')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data ultima modifica')),
            ],
            options={
                'verbose_name': 'Membro del Team',
                'verbose_name_plural': 'Membri del Team',
                'ordering': ['order', 'name'],
            },
        ),
    ]
