# Generated by Django 5.1.4 on 2025-09-13 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_aboutus_teammember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('commerciale', 'Diritto Commerciale'), ('privato', 'Diritto Civile'), ('lavoro', 'Diritto del Lavoro'), ('penale', 'Diritto Penale')], max_length=20, verbose_name='Categoria'),
        ),
    ]
